name: Health Check

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  monitor-health:
    runs-on: ubuntu-latest

    steps:
      - name: Check Service URL
        uses: jtalk/url-health-check-action@v3
        with: 
          url: https://lingering-surf-9956.fly.dev/